//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelloWorld.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        public static string _do {
            get {
                return ResourceManager.GetString("_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string A {
            get {
                return ResourceManager.GetString("A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Overview.
        /// </summary>
        public static string App_Overview {
            get {
                return ResourceManager.GetString("App_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye.
        /// </summary>
        public static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string Classic {
            get {
                return ResourceManager.GetString("Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Overview.
        /// </summary>
        public static string Environment_Overview {
            get {
                return ResourceManager.GetString("Environment_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto.
        /// </summary>
        public static string Goto {
            get {
                return ResourceManager.GetString("Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Panel.
        /// </summary>
        public static string Login_Panel {
            get {
                return ResourceManager.GetString("Login_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pakistan.
        /// </summary>
        public static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References &amp; Docs.
        /// </summary>
        public static string References_And_Documents {
            get {
                return ResourceManager.GetString("References_And_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Management Portal.
        /// </summary>
        public static string Release_Management_Portal {
            get {
                return ResourceManager.GetString("Release_Management_Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reshaping.
        /// </summary>
        public static string Reshaping {
            get {
                return ResourceManager.GetString("Reshaping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reshaping the way wo do things!.
        /// </summary>
        public static string Reshaping_the_way_we_do_things {
            get {
                return ResourceManager.GetString("Reshaping_the_way_we_do_things", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the.
        /// </summary>
        public static string the {
            get {
                return ResourceManager.GetString("the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to things.
        /// </summary>
        public static string things {
            get {
                return ResourceManager.GetString("things", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Arab Emirates.
        /// </summary>
        public static string United_Arab_Emirates {
            get {
                return ResourceManager.GetString("United_Arab_Emirates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        public static string United_Kingdom {
            get {
                return ResourceManager.GetString("United_Kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View, Add, Edit and Delete Releases Environments and Client....
        /// </summary>
        public static string View_Add_Edit_And_Delete_Release_Environment_Client {
            get {
                return ResourceManager.GetString("View_Add_Edit_And_Delete_Release_Environment_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Download the authentic References....
        /// </summary>
        public static string View_and_Download_the_authentic_References {
            get {
                return ResourceManager.GetString("View_and_Download_the_authentic_References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the latest Application Overview.
        /// </summary>
        public static string View_the_latest_Application_Overview {
            get {
                return ResourceManager.GetString("View_the_latest_Application_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the latest Environments Overview.
        /// </summary>
        public static string View_the_latest_Environments_Overview {
            get {
                return ResourceManager.GetString("View_the_latest_Environments_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to way.
        /// </summary>
        public static string way {
            get {
                return ResourceManager.GetString("way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we.
        /// </summary>
        public static string we {
            get {
                return ResourceManager.GetString("we", resourceCulture);
            }
        }
    }
}
